backend/controllers/CarController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\RogUserCar;
use common\models\RogCarType;
use common\models\RogUser;


use yii\helpers\ArrayHelper;
use common\models\RogTypeWheel;
use backend\models\SearchRogUserCar;
use common\models\RogCarDescription;
use common\models\RogUserCarSearch;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * CarController implements the CRUD actions for RogUserCar model.
 */
class CarController extends Controller
{
    /**
     * {@inheritdoc}
     */

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public $upload_foler = 'uploads';

    /**
     * Lists all RogUserCar models.
     * @return mixed
     */
    public function actionIndex()

    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $searchModel = new SearchRogUserCar();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCarcompany($id)
    {
        $model = RogUserCar::findOne($id);

        $user_id = Yii::$app->user->id;


        /*var_dump($id);
        die();*/

        $request = Yii::$app->request;
        $users_id = $request->post('user_id');

        /*var_dump($id);
        die();*/

        $searchModel = new RogUserCarSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider
            ->query
            ->andFilterWhere(['in', 'user_id', $id]);


        return $this->render('car_company', [
            'model' => $model,


            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'cartypes' => $this->getCarTypes(),
        ]);
    }

    /**
     * Displays a single RogUserCar model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RogUserCar model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = new RogUserCar();

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->pic_car = $model->uploadMultiple($model, 'pic_car');
            }

            $model->save();

            //return $this->redirect(['view', 'id' => $model->car_id]);
            return $this->redirect(['view', 'id' => $model->car_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'cartypes' => $this->getCarTypes(),
        ]);
    }

    /**
     * Updates an existing RogUserCar model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $model = $this->findModel($id);


        $cardes = ArrayHelper::map($this->getCardes($model->type_wheel), 'id', 'name');
        $user = ArrayHelper::map($this->getUser($model->user_id), 'user_id', 'username');
        $cartype = ArrayHelper::map($this->getUser($model->car_type), 'car_type_id', 'name');

        $oldimage = $model->pic_car;
        $imagesexplode = explode(",", $oldimage);

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {

                $model->pic_car = $model->uploadMultiple($model, 'pic_car');


                $photo = $model->pic_car;

                //echo $photo;
                //die();

                if ($photo != $oldimage) {

                    foreach ($imagesexplode as $images) {
                        unlink(Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/' . $images);
                    }
                    if ($model->save()) {
                        return $this->redirect(['view', 'id' => $model->car_id]);
                    }
                } else if ($photo == $oldimage) {

                    if ($model->save()) {
                        return $this->redirect(['view', 'id' => $model->car_id]);
                    }
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'user' => $user,
            'cartype' => $cartype,
            'cartypes' => $this->getCarTypes(),
            'cardes' => $cardes,


        ]);
    }

    /**
     * Deletes an existing RogUserCar model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = RogUserCar::findOne($id);

        $images = explode(",", $model->pic_car);
        if ($model->pic_car != null) {

            foreach ($images as $image) {
                unlink(Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/' . $image);
            }

            $this->findModel($id)->delete();
        } else {

            $this->findModel($id)->delete();
            //echo 'ไม่สามารถลบข้อมูลได้';
            //die();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the RogUserCar model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return RogUserCar the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

        if (($model = RogUserCar::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetUser()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $user_id = $parents[0];
                $out = $this->getUser($user_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getUser($id)
    {
        $datas = RogUser::find()->where(['user_id' => $id])->all();
        return $this->MapData($datas, 'user_id', 'username');
    }

    public function actionGetCartypess()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $user_id = $parents[0];
                $out = $this->getUser($user_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getCartypess($id)
    {
        $datas = RogUser::find()->where(['car_type' => $id])->all();
        return $this->MapData($datas, 'car_type_id', 'name');
    }


    public function getCarTypes()
    {
        if (($model = RogCarType::find()) !== null) {
            return ArrayHelper::map(
                RogCarType::find()->orderBy(['index_sort' => SORT_ASC])->asArray()->all(),
                'car_type_id',

                function ($model) {
                    if ($model['name'] == $model['description']) return $model['name'];
                    else return $model['name'] . ' - ' . $model['description'];
                }
            );
        }

        return array(-1, 'No car data');
    }


    public function actionGetCardes()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $typewheel = $parents[0];
                $out = $this->getCardes($typewheel);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getCardes($id)
    {
        $datas = RogCarDescription::find()->where(['type_wheel_id' => $id])->all();
        return $this->MapData($datas, 'car_des_id', 'car_des_name');
    }


    protected function MapData($datas, $fieldId, $fieldName)
    {
        $obj = [];
        foreach ($datas as $key => $value) {
            array_push($obj, ['id' => $value->{$fieldId}, 'name' => $value->{$fieldName}]);
        }
        return $obj;
    }

    /*public function getCarTypes()
    {
        if (($model = RogCarType::find()) !== null) {
            return ArrayHelper::map(
                RogCarType::find()->orderBy(['index_sort' => SORT_ASC])->asArray()->all(),
                'car_type_id',
                function ($model) {
                    if ($model['name'] == $model['description']) return $model['name'];

frontend/views/car/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\RogCarType;
use kartik\color\ColorInput;
use common\models\Provinces;
use yii\helpers\ArrayHelper;
use kartik\widgets\DepDrop;
use common\models\RogTypeWheel;
use kartik\select2\Select2;
use yii\helpers\Url;

$rogcartype = ArrayHelper::map(RogCarType::find()->asArray()->all(), 'car_type_id', 'name');
$typewheel = ArrayHelper::map(RogTypeWheel::find()->asArray()->all(), 'type_wheel_id', 'type_wheel_name');
$provinces = ArrayHelper::map(Provinces::find()->orderBy('name_th')->asArray()->all(), 'id', 'name_th');
$car_des = $this->context->getCarSearch();
$id = yii::$app->user->identity->id;
/*
$listData = [];
 $options['options' => []];$form->field($model, 'car_type')->dropDownList($listData,$options)
$options[] = ['options' => []];

$fit_list = RogCarType::find()->all();

foreach($fit_list as $item)
{
    $listData[$item['car_type_id']] = 
    ($item['name'] == $item['description']) 
        ? $item['name'] 
        : $item['name'].' - '.$item['description'];
    
    $options['options'][$item['car_type_id']] = ['data-image' => $item->photoViewer];

$form->field($model, 'chassis_number')->textInput(['maxlength' => true])
$form->field($model, 'engine_number')->textInput(['maxlength' => true])

}*/
?>

<div class="rog-user-car-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="card2">
        <div class="card-body">

        <?= 
            $form
                ->field($model, 'car_search_level')
                ->hiddenInput(['maxlength' => true, 'value' => $model->getDefaultLevel()])
                //->input('', ['placeholder' => ""])
                ->label(false) 
        ?>

        <?= $form->field($model, 'user_id')
            ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $id])
            ->label(false)
        ?>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4">
                <?=     
                    $form
                        ->field($model, 'car_des')
                        ->widget(Select2::classname(), [
                            'data' => $car_des,
                            'model' => $model,
                            'attribute' => 'car_des',
                            'language' => 'th',
                            'options' => ['placeholder' => 'เลือกประเภทรถ'],
                            'pluginOptions' => [
                                'allowClear' => true,
                                //'multiple' => true,
                            ],                    
                    ])    
                    ->label('เลือกประเภทรถ', ['class' => '', 'style' => 'color:red'])         
                ?>
            </div>
                        
                        
            <!--<div class="col-xs-12 col-sm-6 col-md-4">
                    <?=''
                        /*$form
                            ->field($model, 'type_wheel')
                            ->label('ชนิดรถ')
                            ->dropdownList($typewheel, [
                                'id' => 'ddl-type_wheel',
                                'prompt' => 'เลือกชนิดรถ'
                            ])
                    */?>
                </div>
                            
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <?=''
                        /*$form
                            ->field($model, 'car_des')
                            ->widget(DepDrop::classname(), [
                                'options' => ['id' => 'ddl-cardes'],
                                'data' => $cardes,
                                'pluginOptions' => [
                                    'depends' => ['ddl-type_wheel'],
                                    'placeholder' => 'เลือกรายละเอียด...',
                                    'url' => Url::to(['/car/get-cardes'])
                                ]
                            ]);
                    */?>
            </div>-->
                                
        </div>



        <?= $form->field($model, 'pic_car[]')
            ->fileInput(['multiple' => true])
            ->label('รูปภาพรถหน้าเฉียง หลังเฉียงของฉัน  (เลือกได้ 2 ภาพเท่านั้น)', ['class' => '', 'style' => 'color:red'])
             ?>
        <div class="well">
            <?= $model->getPhotosViewerUpdate(); ?>
        </div>

        <br>
                
        <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
        <?= $form->field($model, 'car_explanation')->textarea(['rows' => 7]) ?>
        </div>
        </div>          

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?= $form->field($model, 'plate_number')->textInput(['maxlength' => true])
                   ->textInput()->input('', ['placeholder' => "ตัวอย่าง กข-1234, 80-1234"]);  ?>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <?= $form->field($model, 'plate_province')->textInput(['maxlength' => true]) 
                ->dropdownList($provinces, [                
                    'prompt' => 'เลือกจังหวัด'
                ])
                ?>
            </div>       
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'manufacturer_txt')
                        ->textInput(['maxlength' => true])
                ?>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'color')
                        ->widget(ColorInput::classname(), [
                            'options' =>
                            ['placeholder' => 'Select color ...'],
                        ])
                ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?= $form->field($model, 'carry_weight')->textInput(['maxlength' => true])
                    ->hint('หน่วยเป็นตัน (1 ตัน = 1000 กิโลกรัม)')
                    ->label('น้ำหนักบรรทุก (ตัน)', ['class' => '', 'style' => 'color:red'])  ?>
            </div>
        </div>

        <hr>

        <h3>ประกันภัยสินค้า</h3>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">

                <?php
                if (!$model->is_insured) $model->is_insured = 0;
                ?>
                <?=
                    $form
                        ->field($model, 'is_insured')
                        ->radioList([0 => 'ไม่มีประกันภัยสินค้า', 1 => 'มีประกันภัยสินค้า'])
                        ->label(false)
                ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'insurance_company')
                        ->textInput(['maxlength' => true])
                ?>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'insured_amount')
                        ->textInput(['maxlength' => true])
                ?>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'car_services')
                        ->textarea(['maxlength' => true, 'rows' => 6])
                        ->hint('เช่น ลำเลียงสินค้าลง')
                ?>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <?=
                    $form
                        ->field($model, 'car_service_tos')
                        ->textarea(['maxlength' => true, 'rows' => 6])
                //->hint('') 
                ?>
            </div>
        </div>

        <?=
            $form
                ->field($model, 'created_date')
                ->hiddenInput([
                    'readonly' => true,
                    'value' => (($model->created_date != null) && ($model->created_date != '0000-00-00 00:00:00')) ? $model->created_date : date('Y-m-d H:i:s')
                ])
                ->label(false)
        ?>

        <?=
            $form
                ->field($model, 'updated_date')
                ->hiddenInput([
                    'readonly' => true,
                    'value' => date('Y-m-d H:i:s')
                ])
                ->label(false)
        ?>

        <div class="form-group">
            <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
        </div>
        
    </div>
</div>
        

    <?php ActiveForm::end(); ?>

</div>

frontend/views/car/_search.php
<?php

use common\models\Amphures;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Provinces;
use common\models\RogCarDescription;
use common\models\RogTypeWheel;
use yii\helpers\Url;

use kartik\depdrop\DepDrop;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model frontend\models\RogUserCarSearch */
/* @var $form yii\widgets\ActiveForm */
$typewheel = ArrayHelper::map(RogTypeWheel::find()->asArray()->all(), 'type_wheel_id', 'type_wheel_name');
$rogtypewheel = ArrayHelper::map(RogTypeWheel::find()->asArray()->all(), 'type_wheel_id', 'type_wheel_name');
$rogcardes = ArrayHelper::map(RogCarDescription::find()->asArray()->all(), 'car_des_id', 'car_des_name');
$provinces = ArrayHelper::map(Provinces::find()->asArray()->all(), 'id', 'name_th');
$dprovinces = ArrayHelper::map(Provinces::find()->asArray()->all(), 'id', 'name_th');
$amphures = ArrayHelper::map(Amphures::find()->asArray()->all(), 'id', 'name_th');
$carsearch = $this->context->getCarSearch();

?>


<script type="text/javascript">
    $(document).ready(function() {

        function showTextStatus(status) {
            return status == 'true' ? "(แตะเพื่อย่อ)" : "(แตะเพื่อขยาย)";
        }

        function loopCheckedValue() {
            var selectedLanguage = []
            $('input[type="checkbox"]:checked').each(function() {
                

                var text = $('span#boxitem' + this.value).html();
                selectedLanguage.push(text);
            });
            return selectedLanguage;
        }

        function showCollapsHead(selected, textStat) {
            $('#divResult').html(selected.length + "\n" + "รายการ / ประเภทรถที่เลือก: " + selected + textStat);
        }

        function event(type) {
            var stat = $("#divResult[aria-expanded]").attr('aria-expanded') == "true";
            var stringStat = type == "exp" ? showTextStatus(""+!stat+"") : showTextStatus(""+stat+"");
            var selected = loopCheckedValue();
            
            if (type == "init") {
                if (selected.length != 0)  { showCollapsHead(selected, stringStat); } 
                else { return; }
            } else { showCollapsHead(selected, stringStat); }  
        }

        $("#divResult[aria-expanded]").click(function() {
            event("exp")
        });

        $('input[type="checkbox"]').click(function() {
            event("chk")
        });
        event("init")
        
    });

</script>






<div class="rog-user-car-search">

    <?php

    $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>



    <!--<div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div id="w1" class="panel-group collapse in" aria-expanded="true" style="">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">

                            <a class="collapse-toggle" href="#w1-collapse1" data-toggle="collapse" data-parent="#w1" aria-expanded="false"  class="divResult" id="divResult">เลือกประเภทรถขนส่ง (แตะเพื่อขยาย)</a>


                        </h4>
                    </div>

                    <div id="w1-collapse1" class="panel-collapse collapse" style="">
                        <div class="panel-body" id="divR"> 
                            <?=

                                $form
                                    ->field($model, 'car_type')
                                    ->checkBoxList(
                                        $this->context->getCarTypes(),
                                        [
                                            'separator' => '<br>',
                                            'item' => function ($index, $label, $name, $checked, $value) {
                                                $checked = $checked ? 'checked' : '';
                                                return '<div> <span id="boxitem' . $value . '"> <input type="checkbox" value=' . $value . ' name=' . $name . ' ' . $checked  . '>' . $label . '</span></div>';
                                            }
                                        ]
                                    )
                                    ->hint(Html::a('คลิกดูประเภทรถ', ['car-type/index'], ['target' => '_blank', 'class' => 'linksWithTarget']))
                                    ->label(false)
                                    ->hint('เลือกได้หลายรายการ')

                            ?>

                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>-->


    <div class="card2"> 

        <h1 style="padding-left:20px; padding-top:20px;">รถร่วมขนส่ง</h1>    

        <div class="row card-body">     


            <div class="col-md-4">  

            <?=     
                    $form
                        ->field($model, 'car_des')
                        ->widget(Select2::classname(), [
                            'data' => $carsearch,
                            'model' => $model,
                            'attribute' => 'car_des',
                            'language' => 'th',
                            'options' => ['placeholder' => 'เลือกประเภทรถ'],
                            'pluginOptions' => [
                                'allowClear' => true,
                                //'multiple' => true,
                            ],                    
                    ])    
                    ->label(false);                  
                ?>
            </div>  
                        

            <!--<div class="col-md-6">
                <?=
                    $form
                        ->field($model, 'type_wheel')
                        ->label('ชนิดรถ', ['class' => ''])
                        ->dropdownList($this->context->getwheelTypes(), [
                            'id' => 'typewheel',
                            'prompt' => 'เลือกชนิดรถ'
                        ])
                ?>
            </div>  

            <div class="col-md-6">
                <?=
                    $form
                        ->field($model, 'car_des')
                        ->widget(DepDrop::classname(), [
                            'options' => ['id' => 'cardes'],
                            'data' => $cardes,
                            'pluginOptions' => [
                                'depends' => ['typewheel'],
                                'placeholder' => 'เลือกทั้งหมด',
                                'url' => Url::to(['/car/get-cardes'])
                            ]
                        ]);
                ?>
            </div>   -->    

                <div class="col-md-4">
                    <?php echo $form
                        ->field($model, 'pickup_province')
                        ->dropdownList($provinces, ['prompt' => 'เลือกจังหวัดต้นทาง']) 
                        ->label(false);
                        ?>
                </div>  

                <div class="col-md-4">
                    <?php echo $form
                        ->field($model, 'deliver_province')
                        ->dropdownList($dprovinces, ['prompt' => 'เลือกจังหวัดปลายทาง']) 
                        ->label(false);
                        ?>
                </div>  
                            
                            
                            

            <div class="col-sm-6">
                <div class="form-group">
                    <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary btn-block', 'id' => 'btnSubmit']) ?>    

                </div>
            </div>  

            <div class="col-sm-6">
                <div class="form-group">
                            
                    <?= Html::a(
                        'รีเซ็ตค่าค้นหา',
                        ['car/index'],
                        ['class' => 'btn btn-danger btn-block', 'style' => '']
                    ) ?>
                </div>
            </div>
                        <hr>    
                    

                <?php ActiveForm::end();
                ?>  

            <!--<div class="col-xs-12 col-sm-12 col-md-12 ">
                <div class="form-group">
                    <?='' /*Html::a(
                        'ลงประกาศ "หารถขนส่ง"',
                        ['job/create'],
                        ['class' => 'btn btn-info btn-block btn-lg', 'style' => '']
                    ) */?>
                </div>
            </div>-->   
                    

            </div>  

        </div>
</div>

frontend/views/car/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RogUserCarSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Admin Cars';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-car-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'car_id',
            'user_id',
            [
                'attribute'=>'car_type',
                'value'=> function($model) use ($cartypes)
                {
                    return (array_key_exists($model->car_type, $cartypes)) ? $cartypes[$model->car_type] : 'ประเภทรถไม่ถูกต้อง';
                },
            ],
            'plate_number',
            'plate_province',
            'carry_weight',
            'manufacturer_txt',
            'is_insured',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{delete}',
            ],
        ],
    ]); ?>
</div>

frontend/views/car/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RogUserCar */

$this->title = 'เพิ่มรถขนส่งให้บริการของฉัน';
$this->params['breadcrumbs'][] = ['label' => 'รถขนส่ง', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-car-create">
    <div class="card2">
        <div class="card-body">
            <h2><?= Html::encode($this->title) ?></h2>
        </div>
    </div>

    
    <?= $this->render('_form', [
        'model' => $model,
        'cartypes' => $cartypes,
        'amphur' => [],
        'cardes' => [],
    ]) ?>

</div>

frontend/views/car/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RogUserCarSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รถขนส่งพร้อมบริการ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-car-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('ลงทะเบียนรถ', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'car_id',
            //'user_id',
            //'car_type',
            [
                'attribute'=>'car_type',
                'value'=> function($model) use ($cartypes)
                {
                    return (array_key_exists($model->car_type, $cartypes)) ? $cartypes[$model->car_type] : 'ประเภทรถไม่ถูกต้อง';
                },
            ],
            'plate_number',
            'carry_weight',
            //'color',
            //'manufacturer',
            //'chassis_number',
            //'engine_number',
            //'created_date',
            //'updated_date',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
            ],
        ],
    ]); ?>
</div>

frontend/views/car/search.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RogUserCar */

$this->title = 'เพิ่มข้อมูล';
$this->params['breadcrumbs'][] = ['label' => 'การจัดการรถของผู้ใช้', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-car-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_search', [
        'model' => $model,
        'cartypes' => $cartypes,
        'amphur' => [],
        'cardes' => [],
    ]) ?>

</div>