backend/controllers/JobController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\RogJobPost;
use backend\models\SearchRogJobPost;
use common\models\RogUser;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Amphures;
use common\models\Districts;
use common\models\RogCarDescription;
use common\models\RogCarType;

use yii\helpers\ArrayHelper;
use yii\helpers\Json;
/**
 * JobController implements the CRUD actions for RogJobPost model.
 */
class JobController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public $upload_foler = 'uploads';

    /**
     * Lists all RogJobPost models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $searchModel = new SearchRogJobPost();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RogJobPost model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RogJobPost model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = new RogJobPost();


        if ($model->load(Yii::$app->request->post())) {
            if ($model->cartype_valid) {
                $model->cartype_valid = implode(",", $model->cartype_valid);
            }

            if ($model->validate()) {
                $model->photos = $model->uploadMultiple($model, 'photos');
            }

            $model->save();
            //return $this->redirect(['view', 'id' => $model->job_id]);
            return $this->redirect(['view', 'id' => $model->job_id]);
        }
       
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing RogJobPost model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = $this->findModel($id);

        $user = ArrayHelper::map($this->getUser($model->user_id), 'user_id', 'username');
        $amphur = ArrayHelper::map($this->getAmphur($model->pickup_province), 'id', 'name');
        $district = ArrayHelper::map($this->getDistrict($model->pickup_district), 'id', 'name');
        $cardes = ArrayHelper::map($this->getCardes($model->type_wheel), 'id', 'name');
        $damphur = ArrayHelper::map($this->getAmphur($model->deliver_province), 'id', 'name');
        $ddistrict = ArrayHelper::map($this->getDistrict($model->deliver_district), 'id', 'name');

        $oldimage = $model->photos;
        $imagesexplode = explode(",", $oldimage);

        if ($model->load(Yii::$app->request->post())) {
            $model->photos = $model->uploadMultiple($model, 'photos');

            //$oldFile = Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/' . $oldimage;


            if ($model->cartype_valid) {
                $model->cartype_valid = implode(",", $model->cartype_valid);
            }

            if ($model->validate()) {
                
                $model->photos = $model->uploadMultiple($model, 'photos');
                
                $photo = $model->photos;
               
                //echo $photo;
                //die();

                if ( $photo != $oldimage ) {

                    foreach ($imagesexplode as $images) {
                        unlink(Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/' . $images);
                    }
                    if ($model->save()) {
                        return $this->redirect(['view', 'id' => $model->job_id]);
                    }
               
                } else if ($photo == $oldimage) {

                    if ($model->save()) {
                        return $this->redirect(['view', 'id' => $model->job_id]);
                    }
                }
            }

        }

        return $this->render('update', [
            'model' => $model,
            'user' => $user,
            'amphur' => $amphur,
            'district' => $district,
            'damphur' => $damphur,
            'ddistrict' => $ddistrict,
            'cardes' => $cardes,

        ]);
    }

    /**
     * Deletes an existing RogJobPost model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        
        $model = RogJobPost::findOne($id);
        $images = explode(",", $model->photos);


        if ($model->photos != null) {
            
            foreach ($images as $image) {
                unlink(Yii::getAlias('@common/web') . '/' . $this->upload_foler . '/' . $image);
            }
            
            $this->findModel($id)->delete();
        } else {
           
            $this->findModel($id)->delete();
            //echo 'ไม่สามารถลบข้อมูลได้';
            //die();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the RogJobPost model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RogJobPost the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        if (($model = RogJobPost::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetUser()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $user_id = $parents[0];
                $out = $this->getUser($user_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }   

    protected function getUser($id)
    {
        $datas = RogUser::find()->where(['user_id' => $id])->all();
        return $this->MapData($datas, 'user_id', 'username');
    }


    public function actionGetAmphur()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $province_id = $parents[0];
                $out = $this->getAmphur($province_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }  

    public function actionGetDistrict()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $province_id = empty($ids[0]) ? null : $ids[0];
            $amphur_id = empty($ids[1]) ? null : $ids[1];
            if ($province_id != null) {
                $data = $this->getDistrict($amphur_id);
                echo Json::encode(['output' => $data, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionGetCardes()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $typewheel = $parents[0];
                $out = $this->getCardes($typewheel);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getCardes($id)
    {
        $datas = RogCarDescription::find()->where(['type_wheel_id' => $id])->all();
        return $this->MapData($datas, 'car_des_id', 'car_des_name');
    }

    protected function getAmphur($id)
    {
        $datas = Amphures::find()->where(['province_id' => $id])->all();
        return $this->MapData($datas, 'id', 'name_th');
    }

    protected function getDistrict($id)
    {
        $datas = Districts::find()->where(['amphure_id' => $id])->all();
        return $this->MapData($datas, 'id', 'name_th');
    }






    protected function MapData($datas, $fieldId, $fieldName)
    {
        $obj = [];
        foreach ($datas as $key => $value) {
            array_push($obj, ['id' => $value->{$fieldId}, 'name' => $value->{$fieldName}]);
        }
        return $obj;
    }

    public function getCarTypes()

backend/views/job/_form.php
<?php

use common\models\Provinces;
use common\models\RogCarType;
use common\models\RogTypeWheel;
use common\models\RogUser;
use kartik\widgets\DepDrop;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\jui\DatePicker;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model common\models\RogJobPost */
/* @var $form yii\widgets\ActiveForm */

$id = yii::$app->user->identity->id;
$roguser = ArrayHelper::map(RogUser::find()->asArray()->all(), 'user_id', 'username');
$provinces = ArrayHelper::map(Provinces::find()->asArray()->all(), 'id', 'name_th');
$typewheel = ArrayHelper::map(RogTypeWheel::find()->asArray()->all(), 'type_wheel_id', 'type_wheel_name');
$rogcartype = ArrayHelper::map(RogCarType::find()->asArray()->all(), 'car_type_id', 'name');

?>

<div class="rog-job-post-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>

    <?= '' // $form->field($model, 'user_id')->textInput()
    ?>



    <?=
        $form
            ->field($model, 'user_id')
            ->label('ชื่อผู้ใช้งาน')
            ->dropdownList($roguser, [
                'id' => 'ddl-roguser',
                'prompt' => 'เลือกผู้ใช้งาน',
            ])
    ?>

    <?=
        $form
            ->field($model, 'job_search_level')
            ->textInput(['maxlength' => true, 'value' => $model->getDefaultLevel()])
            //->input('', ['placeholder' => ""])
            ->label()
    ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'contact_person')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'contact_person_pickup')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'contact_person_delivery')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'short_description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'full_description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'photos[]')->fileInput(['multiple' => true]) ?>
    <div class="well">
        <?= $model->getPhotosViewerback(); ?>
    </div>



    <!--<?=
            $form
                ->field($model, 'cartype_valid')
                ->label('ประเภทรถขนส่งที่ต้องการ')
                ->dropdownList($rogcartype, [
                    'id' => 'ddl-rogcartype',
                    'prompt' => 'เลือกประเภทรถ',
                ])
        ?>-->


    <hr>

    <?= $form->field($model, 'cartype_valid')->checkboxList($model->getItemSkill())->label(false) ?>

    <h3 style="color:red;">* เลือกประเภทรถขนส่งที่ต้องการ</h3>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'cartype_valid')
                    ->checkBoxList(
                        $this->context->getCarTypes(),
                        ['itemOptions' => $model->cartypeToArray(), 'separator' => '<br>']
                    )
                    ->hint(Html::a('คลิกดูประเภทรถ', ['car-type/index'], ['target' => '_blank', 'class' => 'linksWithTarget']))
                    ->label(false)
                    ->hint('เลือกได้หลายรายการ')
            ?>
        </div>
    </div>




    <?= $form
        ->field($model, 'deliver_date')
        ->widget(DatePicker::classname(), [
            'language' => 'th',
            'dateFormat' => 'yyyy-MM-dd',
            'clientOptions' => [
                'changeMonth' => true,
                'changeYear' => true,
            ],
            'options' => ['class' => 'form-control'],
        ])
    ?>


    <?= $form->field($model, 'pickup_location')->textInput(['maxlength' => true]) ?>

    <hr>

    <h3>ต้นทาง</h3>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_province')
                    ->label('* จังหวัดต้นทาง', ['class' => '', 'style' => 'color:red'])
                    ->dropdownList($provinces, [
                        'id' => 'ddl-province',
                        'prompt' => 'เลือกจังหวัด',
                    ])
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_district')
                    ->widget(DepDrop::classname(), [
                        'options' => ['id' => 'ddl-amphur'],
                        'data' => $amphur,
                        'pluginOptions' => [
                            'depends' => ['ddl-province'],
                            'placeholder' => 'เลือกอำเภอ...',
                            'url' => Url::to(['/job/get-amphur']),
                        ],
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_subdistrict')
                    ->widget(DepDrop::classname(), [
                        'data' => $district,
                        'pluginOptions' => [
                            'depends' => ['ddl-province', 'ddl-amphur'],
                            'placeholder' => 'เลือกตำบล...',
                            'url' => Url::to(['/job/get-district']),
                        ],
                    ]);
            ?>
        </div>


    </div>

    <hr>

    <h3>ปลายทาง</h3>


    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_province')
                    ->label('* จังหวัดปลายทาง', ['class' => '', 'style' => 'color:red'])
                    ->dropdownList($provinces, [
                        'id' => 'ddl-dprovince',
                        'prompt' => 'เลือกจังหวัด',
                    ])
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_district')
                    ->widget(DepDrop::classname(), [
                        'options' => ['id' => 'ddl-damphur'],
                        'data' => $damphur,
                        'pluginOptions' => [
                            'depends' => ['ddl-dprovince'],
                            'placeholder' => 'เลือกอำเภอ...',
                            'url' => Url::to(['/job/get-amphur']),
                        ],
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_subdistrict')
                    ->widget(DepDrop::classname(), [
                        'data' => $ddistrict,
                        'pluginOptions' => [
                            'depends' => ['ddl-dprovince', 'ddl-damphur'],
                            'placeholder' => 'เลือกตำบล...',
                            'url' => Url::to(['/job/get-district']),
                        ],
                    ]);
            ?>
        </div>
    </div>
    <hr>

    <?= $form->field($model, 'deliver_location')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_date')->textInput([
        'readonly' => true,
        'value' => (($model->created_date != null) && ($model->created_date != '0000-00-00 00:00:00')) ? $model->created_date : date('Y-m-d H:i:s'),
    ]) ?>

    <?= $form->field($model, 'updated_date')->textInput([
        'readonly' => true,
        'value' => date('Y-m-d H:i:s'),
    ]) ?>


    <?= $form->field($model, 'is_job_taken')->textInput() ?>

    <?= $form->field($model, 'is_period_job')->textInput() ?>

    <?= $form->field($model, 'is_job_close')->textInput() ?>

    <?= $form->field($model, 'is_job_appear')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>






    <?php ActiveForm::end(); ?>

</div>

backend/views/job/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SearchRogJobPost */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rog-job-post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'job_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'contact_person') ?>

    <?= $form->field($model, 'contact_person_pickup') ?>

    <?php // echo $form->field($model, 'contact_person_delivery') ?>

    <?php // echo $form->field($model, 'short_description') ?>

    <?php // echo $form->field($model, 'full_description') ?>

    <?php // echo $form->field($model, 'photos') ?>

    <?php // echo $form->field($model, 'cartype_valid') ?>

    <?php // echo $form->field($model, 'deliver_date') ?>

    <?php // echo $form->field($model, 'pickup_location') ?>

    <?php // echo $form->field($model, 'pickup_province') ?>

    <?php // echo $form->field($model, 'pickup_district') ?>

    <?php // echo $form->field($model, 'pickup_subdistrict') ?>

    <?php // echo $form->field($model, 'deliver_location') ?>

    <?php // echo $form->field($model, 'deliver_province') ?>

    <?php // echo $form->field($model, 'deliver_district') ?>

    <?php // echo $form->field($model, 'deliver_subdistrict') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'updated_date') ?>

    <?php // echo $form->field($model, 'is_job_taken') ?>

    <?php // echo $form->field($model, 'is_period_job') ?>

    <?php // echo $form->field($model, 'is_job_close') ?>

    <?php // echo $form->field($model, 'is_job_appear') ?>

    <div class="form-group">
        <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('รีเซ็ท', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/job/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RogJobPost */

$this->title = 'เพิ่มข้อมูลงานขนส่ง';
$this->params['breadcrumbs'][] = ['label' => 'การจัดการข้อมูลงานขนส่ง', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-job-post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'amphur' => [],
        'district' => [],
        'damphur' => [],
        'ddistrict' => [],
        'cardes' => [],
    ]) ?>

</div>

backend/views/job/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SearchRogJobPost */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'การจัดการข้อมูลงานขนส่ง';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-job-post-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่มข้อมูล', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'job_id',
            //'user_id',
            [
                'attribute' => 'user_id',
                'value' => 'user.username',
            ],
           
            'title',
            'contact_person',
            'contact_person_pickup',
            'contact_person_delivery',
            'short_description',
            //'full_description',
            //'photos:ntext',
           /* [
                'attribute' =>'photos',
                'format' =>'html',    
                'value' => function($data) {
                   return Html::img(\Yii::$app->request->BaseUrl.'/uploads/'.$data->photos,['width'=> 70]);
                }
            ],*/
            //'cartype_valid',
            //'deliver_date',
            //'pickup_location',
            //'pickup_province',
            [
                'attribute' => 'pickup_province',
                'value' => 'provinces.name_th',
            ],
            //'pickup_district',
            //'pickup_subdistrict',
            //'deliver_location',
            //'deliver_province',
            [
                'attribute' => 'deliver_province',
                'value' => 'dprovinces.name_th',
            ],
            
            'job_search_level',
            //'deliver_district',
            //'deliver_subdistrict',
            //'created_date',
            //'updated_date',
            //'is_job_taken',
            //'is_period_job',
            //'is_job_close',
            //'is_job_appear',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

backend/views/job/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RogJobPost */

$this->title = 'แก้ไขข้อมูลงานขนส่ง : ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'การจัดการข้อมูลงานขนส่ง', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->job_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="rog-job-post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'amphur' => $amphur,
        'district' => $district,
        'damphur' => $damphur,
        'ddistrict' => $ddistrict,
        'cardes' => $cardes,
        
    ]) ?>

</div>

backend/views/job/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\RogJobPost */

Yii::$app->params['og_title']['content'] = $model->title;
Yii::$app->params['og_description']['content'] = $model->getOGDesc();
Yii::$app->params['og_image']['content'] = $model->getFirstPhotoURL();
Yii::$app->params['og_url']['content'] = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'ประกาศหารถ', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="rog-job-post-view">

<h1><?=Html::encode($this->title)?></h1>

<p>
        <?=Html::a('เพิ่มข้อมูล', ['create'], ['class' => 'btn btn-success'])?>
        <?=Html::a('แก้ไข', ['update', 'id' => $model->job_id], ['class' => 'btn btn-primary'])?>
        <?=Html::a('ลบ', ['delete', 'id' => $model->job_id], [
    'class' => 'btn btn-danger',
    'data' => [
        'confirm' => 'คุณต้องการลบรายการนี้หรือไม่?',
        'method' => 'post',
    ],
])?>
    </p>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <p><?=$model->getPhotosViewerback()?></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <p><strong>รายละเอียดงานขนส่ง / การขึ้น ลงสินค้า</strong> : <?=$model->full_description?></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <p><strong>ประเภทสินค้า / รายละเอียด</strong> : <?=$model->short_description?></p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <p><strong>ประเภทรถขนส่งที่ต้องการ</strong><br><?=$model->cartype_text()?></p>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <!-- Your share button code -->
            <div class="fb-share-button"
                data-size="large"
                data-href="<?='https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']?>"
                data-layout="button_count">
            </div>
            <div class="line-it-button"
                data-lang="en"
                data-type="share-a"
                data-ver="2"
                data-url="<?='https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']?>"
                style="display: none;">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <p><strong>ต้นทาง</strong></p>
            <ul>
                <li><strong>สถานที่ : </strong><?=$model->pickup_location?></li>
                <li><?=$model->location_text($model->pickup_province, $model->pickup_district, $model->pickup_subdistrict)?></li>
                <li><strong>ผู้ติดต่อ : </strong><?=$model->contact_person_pickup?></li>
            </ul>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <p><strong>ปลายทาง</strong></p>
            <ul>
                <li><strong>สถานที่</strong> : <?=$model->deliver_location?></li>
                <li><?=$model->location_text($model->deliver_province, $model->deliver_district, $model->deliver_subdistrict)?></li>
                <li><strong>ผู้ติดต่อ : </strong><?=$model->contact_person_delivery?></li>
            </ul>
        </div>
    </div>

    <?='' /* DetailView::widget([
'model' => $model,
'attributes' => [
//'job_id',
//'user_id',
'title',
'full_description',
'contact_person',
//'cartype_valid',
[
'format'=>'raw',
'attribute'=>'cartype_valid',
'value'=>$model->cartype_text(),
],
'short_description',
[
'format'=>'raw',
'attribute'=>'photos',
'value'=>$model->getPhotosViewer(),
],

'pickup_location',
'pickup_province',
'pickup_district',
'pickup_subdistrict',
'contact_person_pickup',

'deliver_location',
'deliver_province',
'deliver_district',
'deliver_subdistrict',
'contact_person_delivery',

'is_period_job',
'is_job_taken',
'is_job_close',
'is_job_appear',

'deliver_date',
'created_date',
'updated_date',
],
])*/?>

</div>