common/models/User.php
<?php

namespace common\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\RogUser;
use backend\models\SearchUser;
use common\models\Amphures;
use common\models\Provinces;
use common\models\RogUserRoute;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * UserController implements the CRUD actions for RogUser model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RogUser models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $searchModel = new SearchUser();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAddRoute($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $provinces = ArrayHelper::map(Provinces::find()->asArray()->all(), 'id', 'name_th');
        $model = RogUserRoute::findOne($id);
        //$model = $this->findModel($id);
        $request = Yii::$app->request;

        if ($request->isPost) {
            $selectedprovinces = $request->post('selectedprovinces');
            $selectedamphur = $request->post('selectedamphur');
            $user_id = $request->post('user_id');

            if ($request->post('step') == 'provinceselector') {
                $redirect = 'select_amphur';

                $provinces = ArrayHelper::map(
                    Provinces::find()
                        ->where(['in', 'id', $selectedprovinces])
                        ->asArray()
                        ->all(),
                    'id',
                    'name_th'
                );

                $amphures = ArrayHelper::map(
                    Amphures::find()
                        ->where(['in', 'province_id', $selectedprovinces])
                        ->asArray()
                        ->all(),
                    'id',
                    'name_th'
                );

                $amphIDs = ArrayHelper::map(
                    Amphures::find()
                        ->asArray()
                        ->all(),
                    'id',
                    'id'
                );

                $selectedamphur = $amphIDs;
            }

            if ($request->post('step') == 'amphurselector') {
                //save

                $userid = Yii::$app->user->id;
                $model = RogUserRoute::findOne($id);
                //$model = $this->findModel($id);
                $this->saveUserRoute($user_id, $selectedamphur);
                //redirect
                //return $this->redirect(['car/route']);
                /*print_r($id);
                die();*/
                return $this->redirect(['user/view', 'id' => $userid]);
            }

            return $this->render($redirect, [
                'provinces' => $provinces,
                'amphures' => $amphures,
                'selectedprovinces' => $selectedprovinces,
                'selectedamphur' => $selectedamphur,
                'model' => $model,
            ]);
        } else {
            $selectedprovinces = [];

            return $this->render('select_province', [
                'provinces' => $provinces,
                'selectedprovinces' => $selectedprovinces,
            ]);
        }
    }

    protected function saveUserRoute($user_id, $amphurids)
    {
        //delete old
        $old_user_route = RogUserRoute::find()
            ->where(['in', 'user_id', $user_id])
            ->all();

        if ($old_user_route != null) {
            foreach ($old_user_route as $route) {
                $route->delete();
            }
        }

        //find all
        $amphures = Amphures::find()
            ->where(['in', 'id', $amphurids])
            ->all();

        //add new
        foreach ($amphures as $amphur) {
            $new_route = new RogUserRoute();
            $new_route->user_id = $user_id;
            $new_route->province = $amphur->province_id;
            $new_route->amphur = $amphur->id;
            $new_route->created_date = date('Y-m-d H:i:s');
            $new_route->updated_date = date('Y-m-d H:i:s');
            $new_route->save();

            //var_dump($new_route); echo '<br>';
        }
        //exit();
    }

    protected function findUserRoute($user_id)
    {
        if (($model = RogUserRoute::find()
            ->where(['in', 'user_id', $user_id])
            ->all()) !== null) {
            return $model;
        }
    }

    public function getAmphuresByProvinceID($provinceID)
    {
        $amphures = ArrayHelper::map(
            Amphures::find()
                ->where(['in', 'province_id', $provinceID])
                ->asArray()
                ->all(),
            'id',
            'name_th'
        );

        return $amphures;
    }

    public function getAmphuresByProvinceName($provinceName)
    {
        $province = Provinces::find()
            ->where(['in', 'name_th', $provinceName])
            ->one();

        $amphures = ArrayHelper::map(
            Amphures::find()
                ->where(['in', 'province_id', $province->id])
                ->asArray()
                ->all(),
            'id',
            'name_th'
        );

        return $amphures;
    }

    protected function getUserPermitData($id)
    {
        if (($model = RogUser::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Displays a single RogUser model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $serviceroutes = ArrayHelper::map(
            RogUserRoute::find()
                ->where(['in', 'user_id', $id])
                ->orderBy(['province' => SORT_ASC])
                ->asArray()
                ->all(),
            'amphur',
            'province'
        );

        $provinces = ArrayHelper::map(
            Provinces::find()
                ->asArray()
                ->all(),
            'id',
            'name_th'
        );

        $amphures = ArrayHelper::map(
            Amphures::find()
                ->asArray()
                ->all(),
            'id',
            'name_th'
        );



        return $this->render('view', [
            'model' => $this->findModel($id),
            'provinces' => $provinces,
            'amphures' => $amphures,
            'serviceroutes' => $serviceroutes,


        ]);
    }

    /**
     * Creates a new RogUser model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = new RogUser();

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->company_pic = $model->uploadMultiple($model, 'company_pic');
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->user_id]);
            }

            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing RogUser model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->company_pic = $model->uploadMultiple($model, 'company_pic');
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->user_id]);
            }

            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionUpdateService($id)
    {
        $model = $this->findModel($id);

        $user_id = Yii::$app->user->id;
        if ($model->user_id != $user_id) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {
                $model->company_pic = $model->uploadMultiple($model, 'company_pic');
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->user_id]);
            }

            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing RogUser model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */

frontend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveField;
use yii\jui\DatePicker;

use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use kartik\widgets\DepDrop;
use common\models\Provinces;
use common\models\Amphures;
use common\models\Districts;

$provinces = ArrayHelper::map(Provinces::find()->asArray()->all(), 'id', 'name_th');

$id = yii::$app->user->identity->id;

/* @var $this yii\web\View */
/* @var $model app\models\RogJobPost */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rog-job-post-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data']
    ]);
    ?>

    <?php
    /*
    <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
    </div>
    </div>
    */
    ?>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'title')
                    ->label('* หัวข้อ', ['class' => '', 'style' => 'color:red'])
                    ->textInput(['maxlength' => true])
            //->hint('text')
            ?>
        </div>

        <div class="col-xs-12 col-sm-12/ col-md-12">
            <?=
                $form
                    ->field($model, 'full_description')
                    ->textarea(['maxlength' => true, 'rows' => 6])
            ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'contact_person')
                    ->textInput(['maxlength' => true,])
                    ->hint('ชื่อ / เบอร์ติดต่อ ตัวอย่าง : คุณเก่ง 08x-xxx-xxxx')
            ?>
        </div>
    </div>

    <hr>

    <h3 style="color:red;">* เลือกประเภทรถขนส่งที่ต้องการ</h3>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'cartype_valid')
                    ->checkBoxList(
                        $this->context->getCarTypes(),
                        ['itemOptions' => $model->cartypeToArray(), 'separator' => '<br>']
                    )
                    ->hint(Html::a('คลิกดูประเภทรถ', ['car-type/index'], ['target' => '_blank', 'class' => 'linksWithTarget']))
                    ->label(false)
                    ->hint('เลือกได้หลายรายการ')
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'short_description')
                    ->textarea(['maxlength' => true, 'rows' => 6])
            ?>
        </div>
    </div>

    <?= $form->field($model, 'photos[]')->fileInput(['multiple' => true]) ?>
    <div class="well">
        <?= $model->getPhotosViewer(); ?>
    </div>

    <hr>

    <h3>ต้นทาง</h3>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'pickup_location')
                    ->textarea(['maxlength' => true])
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_province')
                    ->label('* จังหวัดต้นทาง', ['class' => '', 'style' => 'color:red'])
                    ->dropdownList($provinces, [
                        'id' => 'ddl-province',
                        'prompt' => 'เลือกจังหวัด'
                    ])
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_district')
                    ->widget(DepDrop::classname(), [
                        'options' => ['id' => 'ddl-amphur'],
                        'data' => $amphur,
                        'pluginOptions' => [
                            'depends' => ['ddl-province'],
                            'placeholder' => 'เลือกอำเภอ...',
                            'url' => Url::to(['/job/get-amphur'])
                        ]
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'pickup_subdistrict')
                    ->widget(DepDrop::classname(), [
                        'data' => $district,
                        'pluginOptions' => [
                            'depends' => ['ddl-province', 'ddl-amphur'],
                            'placeholder' => 'เลือกตำบล...',
                            'url' => Url::to(['/job/get-district'])
                        ]
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'contact_person_pickup')
                    ->textInput(['maxlength' => true])
                    ->hint('ชื่อ / เบอร์ติดต่อ ตัวอย่าง : คุณเก่ง 08x-xxx-xxxx')
            ?>
        </div>
    </div>

    <hr>

    <h3>ปลายทาง</h3>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'deliver_location')
                    ->textarea(['maxlength' => true])
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_province')
                    ->label('* จังหวัดปลายทาง', ['class' => '', 'style' => 'color:red'])
                    ->dropdownList($provinces, [
                        'id' => 'ddl-dprovince',
                        'prompt' => 'เลือกจังหวัด'
                    ])
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_district')
                    ->widget(DepDrop::classname(), [
                        'options' => ['id' => 'ddl-damphur'],
                        'data' => $damphur,
                        'pluginOptions' => [
                            'depends' => ['ddl-dprovince'],
                            'placeholder' => 'เลือกอำเภอ...',
                            'url' => Url::to(['/job/get-amphur'])
                        ]
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-4">
            <?=
                $form
                    ->field($model, 'deliver_subdistrict')
                    ->widget(DepDrop::classname(), [
                        'data' => $ddistrict,
                        'pluginOptions' => [
                            'depends' => ['ddl-dprovince', 'ddl-damphur'],
                            'placeholder' => 'เลือกตำบล...',
                            'url' => Url::to(['/job/get-district'])
                        ]
                    ]);
            ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?=
                $form
                    ->field($model, 'contact_person_delivery')
                    ->textInput(['maxlength' => true])
                    ->hint('ชื่อ / เบอร์ติดต่อ ตัวอย่าง : คุณเก่ง 08x-xxx-xxxx')
            ?>
        </div>
    </div>

    <hr>

    <h3>ความถี่ของงาน</h3>

    <div class="row">

        <div class="col-xs-12 col-sm-4 col-md-4">

            <?php
            if (!$model->is_period_job) $model->is_period_job = 0;
            ?>

            <?=
                $form
                    ->field($model, 'is_period_job')
                    ->radioList([0 => 'งานครั้งเดียว', 1 => 'งานประจำ'])
                    ->label(false)
            ?>
        </div>

        <div class="col-xs-12 col-sm-8 col-md-8">
            <?= $form
                ->field($model, 'deliver_date')
                ->widget(DatePicker::classname(), [
                    'language' => 'th',
                    'dateFormat' => 'yyyy-MM-dd',
                    'clientOptions' => [
                        'changeMonth' => true,
                        'changeYear' => true,
                    ],
                    'options' => ['class' => 'form-control']
                ])
            ?>
        </div>
    </div>

    <hr>

    <h3>สถานะงาน</h3>

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?php
            if (!$model->is_job_taken) $model->is_job_taken = 0;
            ?>

            <?=
                $form
                    ->field($model, 'is_job_taken')
                    ->radioList([0 => 'ยังไม่ถูกรับ', 1 => 'ถูกรับแล้ว'])
            //->label(false)
            ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?php
            if (!$model->is_job_close) $model->is_job_close = 0;
            ?>

            <?=
                $form
                    ->field($model, 'is_job_close')
                    ->radioList([0 => 'งานยังไม่จบ', 1 => 'จบงานแล้ว'])
            //->label(false)
            ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <?php
            if (!$model->is_job_appear) $model->is_job_appear = 0;
            ?>

            <?=
                $form
                    ->field($model, 'is_job_appear')
                    ->radioList([0 => 'แสดงงานในหน้าค้นหา', 1 => 'ซ่อนงานจากหน้าค้นหา'])
                    //->label(false)
                    ->hint('ยังสามารถเข้าได้จาก url ที่แชร์ไว้')
            ?>
        </div>

    </div>



    <?=
        $form
            ->field($model, 'created_date')
            ->hiddenInput([
                'readonly' => true,
                'value' => (($model->created_date != null) && ($model->created_date != '0000-00-00 00:00:00')) ? $model->created_date : date('Y-m-d H:i:s')
            ])
            ->label(false)
    ?>

    <?=
        $form
            ->field($model, 'updated_date')
            ->hiddenInput([
                'readonly' => true,
                'value' => date('Y-m-d H:i:s')
            ])
            ->label(false)
    ?>

    <?=
        $form
            ->field($model, 'user_id')
            ->hiddenInput(['readonly' => true, 'value' => $id])
            ->label(false)
    ?>

    <div class="form-group" >
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/_form_general.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RogUser */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rog-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <div>
        <p></p>
    </div>

    <div class="card2">
        <h1 align="center" style="padding-top:10px;">กรอกข้อมูล</h1>
        <div class="card-body">
            <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'tel_1')->textInput(['maxlength' => true]) ?>

            <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom :10px">
                <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
            </div>

        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RogUserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rog-user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'company_name') ?>

    <?= $form->field($model, 'company_address') ?>

    <?php // echo $form->field($model, 'company_pic') ?>

    <?php // echo $form->field($model, 'pic_idcard') ?>

    <?php // echo $form->field($model, 'pic_carlic') ?>

    <?php // echo $form->field($model, 'pic_self') ?>

    <?php // echo $form->field($model, 'facebook_id') ?>

    <?php // echo $form->field($model, 'facebook_token') ?>

    <?php // echo $form->field($model, 'citizen_id') ?>

    <?php // echo $form->field($model, 'carlic_id') ?>

    <?php // echo $form->field($model, 'prefix') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'surname') ?>

    <?php // echo $form->field($model, 'middlename') ?>

    <?php // echo $form->field($model, 'dob') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'website') ?>

    <?php // echo $form->field($model, 'line_id') ?>

    <?php // echo $form->field($model, 'tel_1') ?>

    <?php // echo $form->field($model, 'tel_2') ?>

    <?php // echo $form->field($model, 'is_user_findcar') ?>

    <?php // echo $form->field($model, 'is_user_car_owner') ?>

    <?php // echo $form->field($model, 'is_user_verified') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'updated_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RogUserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users Management';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <!--?= Html::a('Create Rog User', ['create'], ['class' => 'btn btn-success']) ?-->
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'user_id',
            'username',
            //'password',
            //'company_name',
            //'company_address:ntext',
            //'company_pic',
            //'pic_idcard',
            //'pic_carlic',
            //'pic_self',
            //'facebook_id',
            //'facebook_token',
            //'citizen_id',
            //'carlic_id',
            //'prefix',
            'name',
            'surname',
            //'middlename',
            'dob',
            //'email:email',
            //'website',
            //'line_id',
            //'tel_1',
            //'tel_2',
            'is_user_findcar',
            'is_user_car_owner',
            'is_user_verified',
            //'created_date',
            //'updated_date',

            //['class' => 'yii\grid\ActionColumn'],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{delete}',
            ],
        ],
    ]); ?>
</div>

frontend/views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RogUser */

$this->title = 'Create Rog User';
//$this->params['breadcrumbs'][] = ['label' => 'Rog Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rog-user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/user/update.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RogUser */

$this->title = 'แก้ไขข้อมูล : ' . $model->name;
//$this->params['breadcrumbs'][] = ['label' => 'Rog Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['profile', 'id' => $model->user_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="rog-user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;


/* @var $this yii\web\View */
/* @var $model app\models\RogUser 

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->user_id], ['class' => 'btn btn-primary']) ?>
<?= Html::a('Delete', ['delete', 'id' => $model->user_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
</p>*/

$this->title = $model->name;
//$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลผู้ใช้', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>


<div class="rog-user-view">
    <div class="container">
        
    <h1><?= Html::encode($this->title) ?></h1>

    <?php

    if ($owner) {
        echo '<p>';
        echo Html::a('แก้ไขรายละเอืยด', ['user/update', 'id' => $model->id], ['class' => 'btn btn-primary']);
        echo '</p>';
    }
    ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'prefix',
            'name',
            'surname',
            'middlename',
            'tel_1',
            'tel_2',
            'line_id',
            'email_contact:email',
            'facebook_token',
            'website',
            
            //'username',
            'created_date',
            'updated_date',
        ],
    ]) ?>

    <hr>

        <div class="service_detail" style="margin-bottom :10px">

            <h2>ข้อมูลกิจการ</h2>

            <?php
            if ($owner) {
                echo '<p>';
                echo Html::a('แก้ไขรายละเอืยด', ['user/update-service', 'id' => $model->id], ['class' => 'btn btn-primary']);
                echo '</p>';
            }
            ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'company_name',
                    'company_address:ntext',
                    'company_pic',
                    'company_explanation'
                ],
            ]) ?>
            </div>

            <hr>
        
        <div class="">
        
            <h2>พื้นที่ให้บริการ</h2>
        
        
                <?php

            $provtran = [];
            foreach($serviceroutes as $key => $servicearea)
            {
                $provtran[$provinces[$servicearea]][$key] = $amphures[$key];
            }
        
            foreach($provtran as $key => $protran)
            {
                echo '<h4>' . $key . '</h4>';
                echo '<p>';
                foreach($provtran[$key] as $distran)
                {
                    echo $distran . ' ';
                }
                echo '</p>';
                echo '<hr>';
            }
            ?>

        </div>
    </div>

</div>



    